# Generated by Django 4.2.27 on 2026-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student_admission_number_admissionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in format: 254712345678', max_length=15, null=True),
        ),
    ]
