# Generated by Django 3.1.1 on 2026-02-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_attendancesummary_classattendance_classattendancerecord_examresult_examschedule_examtype_feebalance_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other')], default='guardian', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for SMS')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.RenameField(
            model_name='feepayment',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='paid_by',
            field=models.CharField(blank=True, help_text='Name of person who paid', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], default='credit', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fee_billed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'CASH'), ('paybill', 'PAYBILL'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payments', to='main_app.student'),
        ),
        migrations.CreateModel(
            name='StudentSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.guardian')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='main_app.student')),
            ],
            options={
                'verbose_name': 'Student SMS',
                'verbose_name_plural': 'Student SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='main_app.student'),
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('term1', 'TERM ONE'), ('term2', 'TERM TWO'), ('term3', 'TERM THREE')], max_length=10)),
                ('score', models.FloatField()),
                ('out_of', models.FloatField(default=100)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.session')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.examtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_results', to='main_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
            options={
                'verbose_name': 'Student Exam Result',
                'verbose_name_plural': 'Student Exam Results',
                'ordering': ['-academic_year__start_year', 'term', 'subject__name'],
                'unique_together': {('student', 'academic_year', 'term', 'exam_type', 'subject')},
            },
        ),
    ]
