# Generated by Django 3.1.1 on 2026-02-28 09:50

from django.db import migrations, models


def populate_session_terms(apps, schema_editor):
    """Populate academic_year and term from existing start_year for old sessions."""
    Session = apps.get_model('main_app', 'Session')
    for s in Session.objects.all():
        m = s.start_year.month
        s.academic_year = s.start_year.year
        if 1 <= m <= 4:
            s.term = 'term1'
        elif 5 <= m <= 8:
            s.term = 'term2'
        else:
            s.term = 'term3'
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20260224_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-academic_year', 'term']},
        ),
        migrations.AddField(
            model_name='session',
            name='academic_year',
            field=models.IntegerField(default=2026, help_text='e.g., 2026'),
        ),
        migrations.AddField(
            model_name='session',
            name='term',
            field=models.CharField(choices=[('term1', 'Term I (January-April)'), ('term2', 'Term II (May-August)'), ('term3', 'Term III (September-December)')], default='term1', max_length=10),
        ),
        migrations.RunPython(populate_session_terms, migrations.RunPython.noop),
    ]
