# Generated by Django 3.1.1 on 2026-02-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_session_term_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='e.g., Grade 4 East, Form 2 Blue', max_length=120),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(help_text='e.g., PP1, G1-G6, F1-F4', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(help_text='e.g., Grade 1, Form 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='stage',
            field=models.CharField(choices=[('preprimary', 'Pre-Primary'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('form', 'Form (8-4-4)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course', verbose_name='Class / Grade Level'),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='e.g., 2025')),
                ('term_name', models.CharField(help_text='e.g., Term 1, Term 2, Term 3', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='closed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-academic_year', 'term_name'],
                'unique_together': {('academic_year', 'term_name')},
            },
        ),
        migrations.AddField(
            model_name='classattendance',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to='main_app.academicterm'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='academic_term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this exam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='main_app.academicterm'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this enrollment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main_app.academicterm'),
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term this subject is offered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main_app.academicterm'),
        ),
    ]
