# Generated by Django 3.1.1 on 2026-03-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_mvp_student_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Grade 4 East, Form 2 Blue', max_length=120)),
                ('capacity', models.PositiveIntegerField(default=40, help_text='Maximum number of students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='main_app.session')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='main_app.staff')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='main_app.gradelevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_classes_legacy', to='main_app.stream')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='main_app.stream')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'main_app_course',
                'ordering': ['grade_level__order_index', 'stream__name', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_course',
            field=models.ForeignKey(blank=True, help_text="Only required if target is 'Specific Class'", null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific class', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='promotionrecord',
            name='from_class',
            field=models.ForeignKey(blank=True, help_text='Source class (optional - if null, promotes all classes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='promotionrecord',
            name='to_class',
            field=models.ForeignKey(blank=True, help_text='Target class for promoted students', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_legacy', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main_app.schoolclass'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Class / Grade Level'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='main_app.schoolclass'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
