# Generated by Django 3.1.1 on 2026-03-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20260303_1246'),
        ('main_app', '0013_result_entry_control'),
    ]

    operations = [
    ]
