# Generated by Django 3.1.1 on 2026-03-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20260303_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='feebalance',
            name='due_date',
            field=models.DateField(blank=True, help_text='When payment is due. Used for fee reminder notifications (1 week before).', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='payment_schedule',
            field=models.CharField(choices=[('termly', 'Termly (full term amount)'), ('monthly', 'Monthly (installments)')], default='termly', help_text='Termly: full amount due by due_date. Monthly: installments per month.', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_course',
            field=models.ForeignKey(blank=True, help_text="Only required if target is 'Specific Class'", null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Target Class'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Parent'), (5, 'Finance Officer')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific class', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(help_text='For termly: full payment due. For monthly: first installment due.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.schoolclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='main_app.schoolclass', verbose_name='Class'),
        ),
    ]
