# Generated by Django 4.2.29 on 2026-03-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_school_status_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('student_limit', models.PositiveIntegerField(default=100, help_text='Max students allowed')),
                ('teacher_limit', models.PositiveIntegerField(default=20, help_text='Max teachers allowed')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['student_limit'],
            },
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(help_text='e.g., PP1, G1-G6, F1-F4', max_length=10),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='order_index',
            field=models.PositiveIntegerField(help_text='For promotion sequence'),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plan controls student/teacher limits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='main_app.subscriptionplan'),
        ),
    ]
