# Generated by Django 4.2.29 on 2026-03-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_create_default_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNECReportCardResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opener_marks', models.FloatField(default=0, help_text='Opener exam marks (out of 100)')),
                ('midterm_marks', models.FloatField(default=0, help_text='Midterm exam marks (out of 100)')),
                ('endterm_marks', models.FloatField(default=0, help_text='End-term exam marks (out of 100)')),
                ('average', models.FloatField(default=0, help_text='(Opener + Midterm + Endterm) / 3')),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('points', models.FloatField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(help_text='Term for this result', on_delete=django.db.models.deletion.CASCADE, related_name='knec_report_results', to='main_app.academicterm')),
                ('session', models.ForeignKey(blank=True, help_text='Academic year/session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knec_report_results', to='main_app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knec_report_results', to='main_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knec_report_results', to='main_app.subject')),
            ],
            options={
                'verbose_name': 'KNEC Report Card Result',
                'verbose_name_plural': 'KNEC Report Card Results',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'academic_term')},
            },
        ),
    ]
