# Generated by Django 4.2.29 on 2026-03-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_update_plan_limits_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='main_app.gradelevel'),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
