# Generated by Django 4.2.29 on 2026-03-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_fix_schoolclass_gradelevel_for_school_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='feegroup',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null for legacy; each school has its own fee groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_groups', to='main_app.school'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null for legacy; each school has its own fee types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='main_app.school'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together={('school', 'code')},
        ),
    ]
