# Generated by Django 4.2.29 on 2026-03-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_add_school_to_feetype_feegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null = legacy/global; new schools create their own', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='main_app.school'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null = legacy/global; new schools create their own', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='main_app.school'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('school', 'code')},
        ),
    ]
