# Generated by Django 4.2.29 on 2026-03-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_examtype_school_gradingscale_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subscriptions', to='main_app.subscriptionplan'),
        ),
    ]
