# Generated by Django 4.2.29 on 2026-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_add_expense_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salaries', 'Staff Salaries'), ('supplies', 'School Supplies'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
