# Generated by Django 4.2.29 on 2026-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(blank=True, help_text='Auto-generated from name if empty (e.g., Grade 1 → G1)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='order_index',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-assigned next number if empty', null=True),
        ),
    ]
